# Generated by Django 4.2.2 on 2023-06-28 03:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='idProducto',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='producto',
            old_name='nombreProducto',
            new_name='nombre',
        ),
        migrations.AddField(
            model_name='producto',
            name='categoria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.categoria'),
        ),
        migrations.AddField(
            model_name='producto',
            name='descof',
            field=models.IntegerField(null=True, verbose_name='descuento oferta'),
        ),
        migrations.AddField(
            model_name='producto',
            name='descripcion',
            field=models.CharField(default='sin descripción', max_length=100, verbose_name='descripcion'),
        ),
        migrations.AddField(
            model_name='producto',
            name='descsus',
            field=models.IntegerField(null=True, verbose_name='descuento suscriptor'),
        ),
        migrations.AddField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(default='sinfoto.jpg', upload_to='images/', verbose_name='Imagen'),
        ),
        migrations.AddField(
            model_name='producto',
            name='precio',
            field=models.IntegerField(default=0, verbose_name='precio producto'),
        ),
    ]
